# Generated by Django 4.2.3 on 2023-08-07 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timeline", "0002_post_1_like_1"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post_1", old_name="created_at_1", new_name="created_at",
        ),
    ]
